/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RoutesPlannerRouteImport } from './routes/routes-planner'
import { Route as PublicTransportRouteImport } from './routes/public-transport'
import { Route as LiveTrafficRouteImport } from './routes/live-traffic'
import { Route as IndexRouteImport } from './routes/index'

const RoutesPlannerRoute = RoutesPlannerRouteImport.update({
  id: '/routes-planner',
  path: '/routes-planner',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicTransportRoute = PublicTransportRouteImport.update({
  id: '/public-transport',
  path: '/public-transport',
  getParentRoute: () => rootRouteImport,
} as any)
const LiveTrafficRoute = LiveTrafficRouteImport.update({
  id: '/live-traffic',
  path: '/live-traffic',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/live-traffic': typeof LiveTrafficRoute
  '/public-transport': typeof PublicTransportRoute
  '/routes-planner': typeof RoutesPlannerRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/live-traffic': typeof LiveTrafficRoute
  '/public-transport': typeof PublicTransportRoute
  '/routes-planner': typeof RoutesPlannerRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/live-traffic': typeof LiveTrafficRoute
  '/public-transport': typeof PublicTransportRoute
  '/routes-planner': typeof RoutesPlannerRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/live-traffic' | '/public-transport' | '/routes-planner'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/live-traffic' | '/public-transport' | '/routes-planner'
  id:
    | '__root__'
    | '/'
    | '/live-traffic'
    | '/public-transport'
    | '/routes-planner'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LiveTrafficRoute: typeof LiveTrafficRoute
  PublicTransportRoute: typeof PublicTransportRoute
  RoutesPlannerRoute: typeof RoutesPlannerRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/routes-planner': {
      id: '/routes-planner'
      path: '/routes-planner'
      fullPath: '/routes-planner'
      preLoaderRoute: typeof RoutesPlannerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/public-transport': {
      id: '/public-transport'
      path: '/public-transport'
      fullPath: '/public-transport'
      preLoaderRoute: typeof PublicTransportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/live-traffic': {
      id: '/live-traffic'
      path: '/live-traffic'
      fullPath: '/live-traffic'
      preLoaderRoute: typeof LiveTrafficRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LiveTrafficRoute: LiveTrafficRoute,
  PublicTransportRoute: PublicTransportRoute,
  RoutesPlannerRoute: RoutesPlannerRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
